-- Auto-generated seed from NCPA_Inventory_All.xlsx
DELETE FROM stocktake_lines;
DELETE FROM stocktakes;
DELETE FROM venue_stock;
DELETE FROM items;
DELETE FROM categories;
DELETE FROM venues;

INSERT INTO venues (id, name, sort_order) VALUES (1, 'JBT', 0);
INSERT INTO venues (id, name, sort_order) VALUES (2, 'TATA', 1);
INSERT INTO venues (id, name, sort_order) VALUES (3, 'TET', 2);
INSERT INTO venues (id, name, sort_order) VALUES (4, 'LT', 3);
INSERT INTO venues (id, name, sort_order) VALUES (5, 'GDT', 4);
INSERT INTO venues (id, name, sort_order) VALUES (6, 'OFFICE', 5);

INSERT INTO categories (id, name, sort_order) VALUES (1, 'CONSOLES & MIXERS', 0);
INSERT INTO categories (id, name, sort_order) VALUES (2, 'STAGE RACKS & I/O', 1);
INSERT INTO categories (id, name, sort_order) VALUES (3, 'SYSTEM CONTROL & NETWORKING', 2);
INSERT INTO categories (id, name, sort_order) VALUES (4, 'MAIN PA SPEAKERS', 3);
INSERT INTO categories (id, name, sort_order) VALUES (5, 'STAGE MONITORS', 4);
INSERT INTO categories (id, name, sort_order) VALUES (6, 'AMPLIFIERS', 5);
INSERT INTO categories (id, name, sort_order) VALUES (7, 'SPEAKER HARDWARE & RIGGING', 6);
INSERT INTO categories (id, name, sort_order) VALUES (8, 'BACKLINE', 7);
INSERT INTO categories (id, name, sort_order) VALUES (9, 'WIRELESS SYSTEMS', 8);
INSERT INTO categories (id, name, sort_order) VALUES (10, 'WIRELESS MIC CAPSULES', 9);
INSERT INTO categories (id, name, sort_order) VALUES (11, 'IEM SYSTEMS', 10);
INSERT INTO categories (id, name, sort_order) VALUES (12, 'WIRED MICROPHONES', 11);
INSERT INTO categories (id, name, sort_order) VALUES (13, 'ANTENNA & RF', 12);
INSERT INTO categories (id, name, sort_order) VALUES (14, 'BATTERIES & CHARGING', 13);
INSERT INTO categories (id, name, sort_order) VALUES (15, 'DI BOXES', 14);
INSERT INTO categories (id, name, sort_order) VALUES (16, 'STANDS & HARDWARE', 15);
INSERT INTO categories (id, name, sort_order) VALUES (17, 'CABLES & SNAKES', 16);
INSERT INTO categories (id, name, sort_order) VALUES (18, 'POWER & UPS', 17);
INSERT INTO categories (id, name, sort_order) VALUES (19, 'COMMS & HEADPHONES', 18);

INSERT INTO items (id, name, category_id) VALUES (1, 'ALLEN & HEATH AVANTIS SOLO', 1);
INSERT INTO items (id, name, category_id) VALUES (2, 'AVID VENUE S6L CONSOLE', 1);
INSERT INTO items (id, name, category_id) VALUES (3, 'MIDAS M32 R LIVE', 1);
INSERT INTO items (id, name, category_id) VALUES (4, 'WAVES EMOTION LV1 CLASSIC 64', 1);
INSERT INTO items (id, name, category_id) VALUES (5, 'ALLEN & HEATH GX4816 RACK', 2);
INSERT INTO items (id, name, category_id) VALUES (6, 'AVID STAGE RACK', 2);
INSERT INTO items (id, name, category_id) VALUES (7, 'FOCUSRITE 18I20 INTERFACE', 2);
INSERT INTO items (id, name, category_id) VALUES (8, 'M32R STAGE RACK', 2);
INSERT INTO items (id, name, category_id) VALUES (9, 'WAVES IONIC 24 STAGE RACK', 2);
INSERT INTO items (id, name, category_id) VALUES (10, 'D-LINK DIR-825 AC1200 WI-FI ROUTER', 3);
INSERT INTO items (id, name, category_id) VALUES (11, 'GALAXY 816', 3);
INSERT INTO items (id, name, category_id) VALUES (12, 'NETGEAR GS108E 8-PORT SWITCH', 3);
INSERT INTO items (id, name, category_id) VALUES (13, 'RMS SERVER', 3);
INSERT INTO items (id, name, category_id) VALUES (14, 'D&B V SUB', 4);
INSERT INTO items (id, name, category_id) VALUES (15, 'D&B V10P', 4);
INSERT INTO items (id, name, category_id) VALUES (16, 'D&B VI SUB', 4);
INSERT INTO items (id, name, category_id) VALUES (17, 'D&B Y 10P CENTRE FILL', 4);
INSERT INTO items (id, name, category_id) VALUES (18, 'DNB G SUBS', 4);
INSERT INTO items (id, name, category_id) VALUES (19, 'DNB V 10I TOP', 4);
INSERT INTO items (id, name, category_id) VALUES (20, 'MEYER 900 SUB', 4);
INSERT INTO items (id, name, category_id) VALUES (21, 'MEYER 900LFC BUMPERS', 4);
INSERT INTO items (id, name, category_id) VALUES (22, 'MEYER LEAPORD  SPEAKERS', 4);
INSERT INTO items (id, name, category_id) VALUES (23, 'MEYER UP-4XP FRONTFILL', 4);
INSERT INTO items (id, name, category_id) VALUES (24, 'MEYER UPM -1XP DOOR DLY', 4);
INSERT INTO items (id, name, category_id) VALUES (25, 'MEYER UPQ -1P', 4);
INSERT INTO items (id, name, category_id) VALUES (26, 'MEYER X40', 4);
INSERT INTO items (id, name, category_id) VALUES (27, 'QUEST QSA200I ACTIVE SPEAKER', 4);
INSERT INTO items (id, name, category_id) VALUES (28, 'TURBO SOUND IP1000 SPEAKERS/SUBS', 4);
INSERT INTO items (id, name, category_id) VALUES (29, 'UPJ -1P', 4);
INSERT INTO items (id, name, category_id) VALUES (30, 'D&B E6', 5);
INSERT INTO items (id, name, category_id) VALUES (31, 'D&B M4', 5);
INSERT INTO items (id, name, category_id) VALUES (32, 'DNB MONITORS MAX 2', 5);
INSERT INTO items (id, name, category_id) VALUES (33, 'D&B D20', 6);
INSERT INTO items (id, name, category_id) VALUES (34, 'D&B D30', 6);
INSERT INTO items (id, name, category_id) VALUES (35, 'DNB D40 AMP', 6);
INSERT INTO items (id, name, category_id) VALUES (36, 'MEYER MDM 5000 EU', 6);
INSERT INTO items (id, name, category_id) VALUES (37, 'MEYER MP488 POWER SUPPLY', 6);
INSERT INTO items (id, name, category_id) VALUES (38, 'MEYER UPM MOUNTING BRACKET', 7);
INSERT INTO items (id, name, category_id) VALUES (39, 'CHAIN PULLY', 7);
INSERT INTO items (id, name, category_id) VALUES (40, 'E6 HORIZONTAL BRACKET', 7);
INSERT INTO items (id, name, category_id) VALUES (41, 'MEYER UP-4XP BRACKETS', 7);
INSERT INTO items (id, name, category_id) VALUES (42, 'MEYER UPJ RINGGING YOKE', 7);
INSERT INTO items (id, name, category_id) VALUES (43, 'MEYER UPQ ARRAY PLATE KIT', 7);
INSERT INTO items (id, name, category_id) VALUES (44, 'PIPE CLAMP FOR TV SPIGOT', 7);
INSERT INTO items (id, name, category_id) VALUES (45, 'TV SPIGOT WITH FIXNG PLATE', 7);
INSERT INTO items (id, name, category_id) VALUES (46, 'V 10 P HORIZONTAL BRACKETS', 7);
INSERT INTO items (id, name, category_id) VALUES (47, 'WHITE MP HORIZONTAL BRACKET', 7);
INSERT INTO items (id, name, category_id) VALUES (48, 'AMPEG BASS AMP', 8);
INSERT INTO items (id, name, category_id) VALUES (49, 'FENDER GTR AMP', 8);
INSERT INTO items (id, name, category_id) VALUES (50, 'KC 600 KB AMP', 8);
INSERT INTO items (id, name, category_id) VALUES (51, 'SHURE BELT PACKS', 9);
INSERT INTO items (id, name, category_id) VALUES (52, 'SHURE SINGLE UNIT RECEIVERS/MICS SET', 9);
INSERT INTO items (id, name, category_id) VALUES (53, 'SHURE SVX 24IN/PG58 WIRELESS MIC', 9);
INSERT INTO items (id, name, category_id) VALUES (54, 'SHURE ULX4D RECIEVER', 9);
INSERT INTO items (id, name, category_id) VALUES (55, 'SHURE ULXD CORDLESS', 9);
INSERT INTO items (id, name, category_id) VALUES (56, 'SHURE RPW 118 (BETA 58A)', 10);
INSERT INTO items (id, name, category_id) VALUES (57, 'SHURE RPW 120 (BETA 87A)', 10);
INSERT INTO items (id, name, category_id) VALUES (58, 'ASA 3000EU ANTENNA SPLITTER', 11);
INSERT INTO items (id, name, category_id) VALUES (59, 'SENHEISER IEM  RECIEVER', 11);
INSERT INTO items (id, name, category_id) VALUES (60, 'SENNHEISER IEM BELT PACKS', 11);
INSERT INTO items (id, name, category_id) VALUES (61, 'SENNHEISER IEM COMBINER', 11);
INSERT INTO items (id, name, category_id) VALUES (62, 'AKG C411', 12);
INSERT INTO items (id, name, category_id) VALUES (63, 'AUDIO TECHNICA PZM', 12);
INSERT INTO items (id, name, category_id) VALUES (64, 'DPA 4061 (LAPEL)', 12);
INSERT INTO items (id, name, category_id) VALUES (65, 'DPA 4099', 12);
INSERT INTO items (id, name, category_id) VALUES (66, 'DPA HEADSET', 12);
INSERT INTO items (id, name, category_id) VALUES (67, 'FISHMAN PICK UP', 12);
INSERT INTO items (id, name, category_id) VALUES (68, 'NEUMAN KM 184', 12);
INSERT INTO items (id, name, category_id) VALUES (69, 'SENNHEISER  E604', 12);
INSERT INTO items (id, name, category_id) VALUES (70, 'SENNHEISER E945 MICROPHONE', 12);
INSERT INTO items (id, name, category_id) VALUES (71, 'SENNHEISER GUN MIC', 12);
INSERT INTO items (id, name, category_id) VALUES (72, 'SHURE BETA 52', 12);
INSERT INTO items (id, name, category_id) VALUES (73, 'SHURE BETA 91', 12);
INSERT INTO items (id, name, category_id) VALUES (74, 'SHURE BETA 98', 12);
INSERT INTO items (id, name, category_id) VALUES (75, 'SHURE HEADSET', 12);
INSERT INTO items (id, name, category_id) VALUES (76, 'SHURE LAPEL', 12);
INSERT INTO items (id, name, category_id) VALUES (77, 'SHURE PGA 48LC MICROPHONE', 12);
INSERT INTO items (id, name, category_id) VALUES (78, 'SHURE PODIUM', 12);
INSERT INTO items (id, name, category_id) VALUES (79, 'SHURE PZM', 12);
INSERT INTO items (id, name, category_id) VALUES (80, 'SHURE SM 57', 12);
INSERT INTO items (id, name, category_id) VALUES (81, 'SHURE SM 58', 12);
INSERT INTO items (id, name, category_id) VALUES (82, 'SHURE SM 81', 12);
INSERT INTO items (id, name, category_id) VALUES (83, 'SHURE TWINPLEX HEADSET', 12);
INSERT INTO items (id, name, category_id) VALUES (84, 'SHURE ANTENNA A 2003 UHF', 13);
INSERT INTO items (id, name, category_id) VALUES (85, 'BATTARY CHAGER UNIT OF 8', 14);
INSERT INTO items (id, name, category_id) VALUES (86, 'SENHEISER  I 2015 CHARGING UNIT', 14);
INSERT INTO items (id, name, category_id) VALUES (87, 'SENHEISER BA 2015 BATTERY', 14);
INSERT INTO items (id, name, category_id) VALUES (88, 'SENHEISER POWER SUPPLY ADAPTOR', 14);
INSERT INTO items (id, name, category_id) VALUES (89, 'SHURE SB 900B- A RECHARGABLE BATTERY', 14);
INSERT INTO items (id, name, category_id) VALUES (90, 'BSS DI BOX', 15);
INSERT INTO items (id, name, category_id) VALUES (91, 'UNIKA USB DI BOX', 15);
INSERT INTO items (id, name, category_id) VALUES (92, 'DESK STAND', 16);
INSERT INTO items (id, name, category_id) VALUES (93, 'GTR STAND', 16);
INSERT INTO items (id, name, category_id) VALUES (94, 'KB STAND', 16);
INSERT INTO items (id, name, category_id) VALUES (95, 'MIC STAND BIG', 16);
INSERT INTO items (id, name, category_id) VALUES (96, 'MIC STAND SMALL', 16);
INSERT INTO items (id, name, category_id) VALUES (97, 'SPEAKER STAND', 16);
INSERT INTO items (id, name, category_id) VALUES (98, '08 CH   DETACHABLE SNAKE', 17);
INSERT INTO items (id, name, category_id) VALUES (99, '12 CH  DETACHABLE SNAKE', 17);
INSERT INTO items (id, name, category_id) VALUES (100, '16CH SNAKE', 17);
INSERT INTO items (id, name, category_id) VALUES (101, '8 CH 30 MTR PATCH', 17);
INSERT INTO items (id, name, category_id) VALUES (102, '8CH PATCH SNAKE', 17);
INSERT INTO items (id, name, category_id) VALUES (103, 'DRUM KIT PATCH XLR', 17);
INSERT INTO items (id, name, category_id) VALUES (104, 'JACK TO JACK', 17);
INSERT INTO items (id, name, category_id) VALUES (105, 'JACK TO XLR', 17);
INSERT INTO items (id, name, category_id) VALUES (106, 'SPEAKON', 17);
INSERT INTO items (id, name, category_id) VALUES (107, 'XLR 10 MTR', 17);
INSERT INTO items (id, name, category_id) VALUES (108, 'XLR 30 MTR', 17);
INSERT INTO items (id, name, category_id) VALUES (109, 'XLR 5 MTR', 17);
INSERT INTO items (id, name, category_id) VALUES (110, '3 PHASE ELECTRICAL DISTRIBUTION RACK', 18);
INSERT INTO items (id, name, category_id) VALUES (111, 'APC UPS', 18);
INSERT INTO items (id, name, category_id) VALUES (112, 'ELECTRICAL POWER BOARD', 18);
INSERT INTO items (id, name, category_id) VALUES (113, 'ALT AIR  CLEAR COM', 19);
INSERT INTO items (id, name, category_id) VALUES (114, 'HMD685A SINGLE EAR INTERCOM HEADSET', 19);
INSERT INTO items (id, name, category_id) VALUES (115, 'SENNHEISER HEADPHONE HD 200', 19);

INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (6, 1, 1);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (1, 2, 2);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (2, 2, 1);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (4, 3, 1);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (5, 3, 1);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (3, 4, 2);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (6, 5, 1);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (1, 6, 1);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (2, 6, 3);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (6, 7, 1);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (4, 8, 1);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (5, 8, 1);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (3, 9, 4);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (3, 10, 2);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (1, 11, 1);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (2, 11, 1);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (3, 12, 2);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (1, 13, 1);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (2, 13, 1);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (3, 14, 2);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (3, 15, 4);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (4, 15, 2);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (1, 16, 2);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (4, 17, 1);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (5, 18, 2);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (5, 19, 2);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (1, 20, 6);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (2, 20, 3);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (1, 21, 2);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (2, 21, 3);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (1, 22, 20);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (1, 23, 7);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (2, 23, 5);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (1, 24, 2);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (1, 25, 4);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (2, 25, 5);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (1, 26, 2);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (6, 27, 4);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (1, 28, 4);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (1, 29, 2);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (2, 29, 5);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (3, 30, 4);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (4, 30, 2);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (5, 30, 4);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (1, 31, 12);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (2, 31, 10);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (3, 31, 6);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (4, 31, 2);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (5, 32, 3);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (1, 33, 4);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (2, 33, 3);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (3, 33, 5);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (4, 33, 1);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (1, 34, 2);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (4, 34, 2);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (5, 35, 2);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (1, 36, 4);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (1, 37, 2);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (2, 37, 1);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (1, 38, 2);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (3, 39, 1);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (4, 40, 2);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (1, 41, 7);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (2, 41, 5);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (1, 42, 2);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (1, 43, 2);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (2, 43, 5);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (4, 44, 3);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (4, 45, 3);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (3, 46, 4);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (4, 46, 2);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (4, 47, 1);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (1, 48, 1);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (2, 48, 1);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (1, 49, 1);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (2, 49, 1);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (1, 50, 1);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (2, 50, 1);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (1, 51, 8);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (2, 51, 6);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (3, 51, 5);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (4, 51, 2);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (5, 51, 2);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (6, 51, 6);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (6, 52, 3);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (2, 53, 3);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (1, 54, 4);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (2, 54, 3);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (3, 54, 2);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (4, 54, 1);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (5, 54, 1);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (6, 54, 3);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (1, 55, 8);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (2, 55, 6);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (3, 55, 4);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (4, 55, 2);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (5, 55, 2);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (6, 55, 6);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (2, 56, 6);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (2, 57, 3);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (6, 58, 2);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (1, 59, 12);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (2, 59, 8);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (3, 59, 4);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (1, 60, 12);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (2, 60, 8);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (3, 60, 5);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (1, 61, 2);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (3, 61, 1);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (6, 61, 2);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (6, 62, 5);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (1, 63, 5);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (2, 63, 5);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (6, 64, 5);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (6, 65, 20);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (1, 66, 2);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (2, 66, 2);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (6, 66, 2);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (1, 67, 1);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (2, 67, 1);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (1, 68, 2);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (2, 68, 2);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (6, 68, 2);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (1, 69, 5);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (2, 69, 5);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (3, 69, 5);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (6, 70, 2);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (1, 71, 6);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (2, 71, 3);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (3, 71, 3);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (1, 72, 2);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (2, 72, 2);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (3, 72, 2);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (1, 73, 1);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (2, 73, 1);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (1, 74, 2);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (2, 74, 2);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (3, 74, 2);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (1, 75, 8);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (2, 75, 6);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (3, 75, 2);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (4, 75, 2);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (1, 76, 8);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (2, 76, 6);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (3, 76, 2);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (4, 76, 2);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (2, 77, 4);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (1, 78, 2);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (2, 78, 2);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (3, 78, 2);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (4, 78, 2);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (6, 78, 2);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (3, 79, 3);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (4, 79, 2);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (1, 80, 12);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (2, 80, 12);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (3, 80, 10);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (4, 80, 6);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (6, 80, 5);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (1, 81, 16);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (2, 81, 16);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (3, 81, 16);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (4, 81, 8);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (6, 81, 5);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (1, 82, 4);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (2, 82, 4);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (3, 82, 6);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (2, 83, 8);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (1, 84, 2);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (2, 84, 2);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (6, 84, 2);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (2, 85, 1);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (3, 85, 1);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (1, 90, 14);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (2, 90, 12);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (3, 90, 8);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (4, 90, 4);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (2, 91, 6);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (1, 92, 4);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (2, 92, 4);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (3, 92, 6);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (4, 92, 2);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (1, 93, 3);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (2, 93, 2);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (1, 94, 2);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (2, 94, 2);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (6, 94, 1);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (1, 95, 20);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (2, 95, 23);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (3, 95, 14);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (4, 95, 2);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (6, 95, 5);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (1, 96, 6);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (2, 96, 23);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (3, 96, 9);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (4, 96, 5);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (6, 96, 5);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (1, 97, 2);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (2, 97, 2);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (3, 97, 2);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (2, 98, 2);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (2, 99, 2);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (1, 100, 4);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (2, 100, 3);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (3, 100, 2);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (4, 100, 1);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (2, 101, 1);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (1, 102, 4);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (2, 102, 4);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (3, 102, 2);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (1, 103, 1);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (3, 103, 1);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (1, 104, 10);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (2, 104, 12);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (3, 104, 11);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (4, 104, 5);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (5, 104, 2);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (6, 105, 8);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (1, 106, 12);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (2, 106, 10);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (3, 106, 8);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (4, 106, 2);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (1, 107, 28);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (2, 107, 40);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (3, 107, 27);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (4, 107, 7);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (5, 107, 10);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (2, 108, 3);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (1, 109, 16);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (2, 109, 20);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (3, 109, 15);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (4, 109, 4);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (5, 109, 2);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (1, 110, 1);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (2, 110, 1);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (1, 111, 3);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (2, 111, 2);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (3, 111, 1);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (4, 111, 1);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (1, 112, 12);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (2, 112, 11);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (3, 112, 11);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (4, 112, 4);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (1, 113, 7);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (2, 113, 7);
INSERT INTO venue_stock (venue_id, item_id, expected_qty) VALUES (6, 115, 3);
